basic.pause(6700)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)
basic.pause(10000)
maqueen.motor_stop(maqueen.Motors.ALL)
basic.pause(20000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)
basic.pause(5000)
maqueen.motor_stop(maqueen.Motors.ALL)
basic.pause(10000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 255)
basic.pause(500)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 50)
basic.pause(50)
maqueen.motor_stop(maqueen.Motors.ALL)
basic.pause(6000)
maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 255)
basic.pause(500)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)