basic.pause(4500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(6700)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(13500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(3400)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(6700)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 255)
basic.pause(340)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 50)
basic.pause(40)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(4000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 255)
basic.pause(340)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(3000)
